twig:
  form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  file_name_pattern: "*.twig"
  globals:
    recaptcha_public_key: "%env(RECAPTCHA_PUBLIC_KEY)%"

when@test:
  twig:
    strict_variables: true
